#!/bin/sh

set -e

. /usr/share/debconf/confmodule

db_input high nixstatsagent/api_host || :
db_input high nixstatsagent/api_path || :
db_input high nixstatsagent/user || :
db_input high nixstatsagent/server || :
db_input high nixstatsagent/server_auto || :
db_go
